output "cluster_id" {
  description = "EKS cluster ID."
  value       = aws_eks_cluster.aws_eks.id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = aws_eks_cluster.aws_eks.endpoint
}

# output "cluster_security_group_id" {
#   description = "Security group ids attached to the cluster control plane."
#   value       = aws_eks_cluster.aws_eks.cluster_security_group_id
# }

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = eks-cluster.kubeconfig
# }

# output "config_map_aws_auth" {
#   description = "A kubernetes configuration to authenticate to this EKS cluster."
#   value       = eks-cluster.config_map_aws_auth
# }

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.eks_cluster_name
}